# API для кластера <cluster> будет доступно по http_addr/<cluster>/...
http_addr: ":6029"
# Адрес метрик соломона и pprof'а (:6060 - дефолтный адрес pprof).
debug_http_addr: ":6060"

# Максимальное время обработки http запроса.
# Дефолт - 2m секунд.
http_handler_timeout: 2m

# Максимальный размер входного файла.
# Дефолтное значение - 10485760 (10 Mb)
max_excel_file_size_bytes: 104857600 # (100 MB)

# Список обслуживаемых инстансом кластеров.
# При добавлении нового кластера приложение нужно передеплоить.
# Каждый кластер имеет кластер-специфичные настройки.
clusters:
  - proxy: hahn
