apiVersion: v1
kind: Service
metadata:
  name: "ytsaurus-excel-exporter-svc"
  labels:
    {{- include "ytsaurus-excel-chart.exporterLabels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.metricsPort }}
      targetPort: metrics
      protocol: TCP
      name: mertics
  selector:
    {{- include "ytsaurus-excel-chart.exporterSelectorLabels" . | nindent 4 }}
