name: Build and Publish Docker image

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'
      - name: Build Service
        run: |
          go build -o ./uploader/cmd/excel-uploader/ -a -v -mod=readonly go.ytsaurus.tech/yt/microservices/excel/uploader/... 
          go build -o ./uploader/cmd/excel-exporter/ -a -v -mod=readonly go.ytsaurus.tech/yt/microservices/excel/exporter/... 
          ./uploader/build/docker/build.sh --image-cr  ghcr.io/ --image-tag latest
          ./exporter/build/docker/build.sh --image-cr  ghcr.io/ --image-tag latest
      - name: 'Build Inventory Image'
        run: |
          cd uploader/build/docker
          docker build . --tag ghcr.io/spiner2000/ytsaurus-excel-uploader:latest
          docker push ghcr.io/spiner2000/ytsaurus-excel-uploader:latest